import os
import pathlib

base_path = pathlib.Path(r"c:\Users\sergio.rebollo\Desktop\UPV\TFM")

directories = [
    "data/raw",
    "data/processed",
    "data/external",
    "config",
    "src/data",
    "src/features",
    "src/models",
    "src/environment",
    "src/evaluation",
    "notebooks",
    "results/figures",
    "results/logs",
    "results/reports"
]

for d in directories:
    (base_path / d).mkdir(parents=True, exist_ok=True)
    if d in ["data/raw", "data/processed", "data/external", "notebooks", "results/figures", "results/logs", "results/reports"]:
        with open(base_path / d / ".gitkeep", "w", encoding="utf-8") as f:
            pass

files = {
    "requirements.txt": '''pandas\nnumpy\nrequests\npython-dotenv\nxgboost\nscikit-learn\npyyaml\nmatplotlib''',
    ".gitignore": '''# Environments\nvenv/\n.env\n\n# Data\ndata/\n!data/**/.gitkeep\n\n# Python cache\n__pycache__/\n*.py[cod]\n*$py.class\n\n# Results & Logs\nresults/\n!results/**/.gitkeep''',
    ".env.example": '''TIINGO_API_KEY=your_tiingo_api_key_here\nFRED_API_KEY=your_fred_api_key_here''',
    "config/settings.yaml": '''project_name: "TFM - Dynamic Risk Management & Portfolio Rebalancing"\ntickers: ['AAPL', 'MSFT', 'SPY']\nstart_date: '2018-01-01'\nend_date: '2023-12-31'\ntimeframe: '4Hour'\ninitial_capital: 100000.0\n\ndata_sources:\n  tiingo:\n    api_url: "https://api.tiingo.com/iex"\n  fred:\n    api_url: "https://api.stlouisfed.org/fred/series/observations"\n\nmodel:\n  xgboost:\n    n_estimators: 100\n    learning_rate: 0.05\n    max_depth: 5\n\nrisk:\n  max_drawdown_per_trade: 0.02\n  atr_multiplier: 2.0''',
    "main_pipeline.py": '''"""\nMain pipeline script for the TFM project.\nOrchestrates the execution of data download, feature engineering,\nmodel training, backtesting, and evaluation.\n"""\n\nimport os\nimport yaml\nfrom pathlib import Path\nfrom dotenv import load_dotenv\n\n# Import custom modules\nfrom src.data.tiingo_loader import TiingoLoader\nfrom src.data.fred_loader import FredLoader\nfrom src.data.data_merger import merge_market_and_macro\nfrom src.features.technical import calculate_rsi, calculate_atr, calculate_sma\nfrom src.features.patterns import detect_bill_williams_fractals, detect_wick_reclaims\nfrom src.models.xgboost_filter import TradeSelectorXGB\nfrom src.models.agent_logic import PortfolioAgent\nfrom src.environment.portfolio import Portfolio\nfrom src.environment.risk_manager import RiskManager\nfrom src.environment.backtester import Backtester\nfrom src.evaluation.metrics import calculate_sharpe_ratio, calculate_max_drawdown, calculate_sortino_ratio\nfrom src.evaluation.plotting import plot_equity_curve\n\ndef load_config(config_path: str = "config/settings.yaml") -> dict:\n    """Loads configuration from a YAML file."""\n    with open(config_path, "r", encoding="utf-8") as file:\n        return yaml.safe_load(file)\n\ndef main():\n    """Main execution flow."""\n    # 1. Initialization and Configuration\n    print("Initializing pipeline...")\n    load_dotenv()\n    config = load_config()\n    \n    # 2. Data Downloading\n    print("Downloading data...")\n    tiingo_loader = TiingoLoader()\n    # df_prices = tiingo_loader.download_historical_data(...)\n    \n    fred_loader = FredLoader()\n    # df_macro = fred_loader.download_macro_data(...)\n    \n    # 3. Data Merging\n    print("Merging market and macro data...")\n    # df_merged = merge_market_and_macro(df_prices, df_macro)\n    \n    # 4. Feature Engineering\n    print("Calculating features...")\n    # Add technical indicators and patterns\n    \n    # 5. Model Training (XGBoost)\n    print("Training XGBoost model...")\n    xgb_model = TradeSelectorXGB()\n    # xgb_model.train_model(...)\n    \n    # 6. Backtesting Simulation\n    print("Running backtest...")\n    portfolio = Portfolio(initial_capital=config.get('initial_capital', 100000.0))\n    risk_manager = RiskManager()\n    agent = PortfolioAgent()\n    \n    backtester = Backtester(portfolio, risk_manager, agent)\n    # backtester.run(df_merged, xgb_model)\n    \n    # 7. Evaluation & Plotting\n    print("Evaluating results...")\n    # sharpe = calculate_sharpe_ratio(...)\n    # plot_equity_curve(...)\n    print("Pipeline execution completed.")\n\nif __name__ == "__main__":\n    main()''',
    "README.md": '''# TFM: Gestión Dinámica del Riesgo y Rebalanceo de Carteras (Renta Variable)\n\nEste proyecto implementa un sistema en Python para la gestión dinámica del riesgo y el rebalanceo de carteras de inversión. Utiliza datos intradiarios de Tiingo, datos macroeconómicos de FRED, XGBoost como filtro de activos, y un Agente Autónomo para el control de la cartera.\n\n## Requisitos\n\n1. Crear un entorno virtual (opcional pero recomendado):\n   ```bash\n   python -m venv venv\n   source venv/bin/activate  # En Windows: venv\\Scripts\\activate\n   ```\n2. Instalar dependencias:\n   ```bash\n   pip install -r requirements.txt\n   ```\n3. Configurar variables de entorno:\n   Copiar `.env.example` a `.env` y configurar las API keys.\n\n## Ejecución\n\nPara ejecutar el pipeline principal:\n\n```bash\npython main_pipeline.py\n```''',
    "src/data/__init__.py": '''"""Data downloading and merging modules."""''',
    "src/features/__init__.py": '''"""Feature engineering modules."""''',
    "src/models/__init__.py": '''"""Predictive models and agent logic."""''',
    "src/environment/__init__.py": '''"""Portfolio, Risk Management, and Backtesting environment."""''',
    "src/evaluation/__init__.py": '''"""Performance metrics and plotting modules."""'''
}

file_contents = {
    "src/data/tiingo_loader.py": '''"""\nModule for downloading intraday data from Tiingo API.\n"""\n\nimport os\nimport pandas as pd\nimport requests\nfrom pathlib import Path\n\nclass TiingoLoader:\n    """\n    Class to load intraday historical prices using Tiingo 'iex' API.\n    """\n    \n    def __init__(self):\n        """\n        Initializes the TiingoLoader, reading the API key from environment variables.\n        """\n        self.api_key = os.getenv("TIINGO_API_KEY")\n        self.base_url = "https://api.tiingo.com/iex"\n        if not self.api_key:\n            raise ValueError("TIINGO_API_KEY is not set in the environment variables.")\n        \n    def download_historical_data(self, ticker: str, start_date: str, resample_freq: str = '1Hour') -> pd.DataFrame:\n        """\n        Downloads historical intraday data for a given ticker and saves it to a CSV file.\n        \n        Args:\n            ticker (str): The stock ticker (e.g., 'AAPL').\n            start_date (str): The start date for data download (YYYY-MM-DD).\n            resample_freq (str): Frequency of the data (e.g., '1Hour', '4Hour').\n            \n        Returns:\n            pd.DataFrame: DataFrame containing the historical prices.\n        """\n        # Placeholder logic for API request and saving to CSV\n        print(f"Downloading Tiingo data for {ticker} from {start_date} at {resample_freq} frequency...")\n        \n        # Save logic using pathlib\n        save_dir = Path("data/raw")\n        save_dir.mkdir(parents=True, exist_ok=True)\n        file_path = save_dir / f"{ticker}_{resample_freq}.csv"\n        \n        # Return empty DataFrame as placeholder\n        return pd.DataFrame()\n''',

    "src/data/fred_loader.py": '''"""\nModule for downloading macroeconomic data from FRED API.\n"""\n\nimport os\nimport pandas as pd\nimport requests\nfrom pathlib import Path\n\nclass FredLoader:\n    """\n    Class to load macroeconomic data (e.g., interest rates, inflation) from FRED.\n    """\n    \n    def __init__(self):\n        """\n        Initializes the FredLoader, reading the API key from environment variables.\n        """\n        self.api_key = os.getenv("FRED_API_KEY")\n        self.base_url = "https://api.stlouisfed.org/fred/series/observations"\n        if not self.api_key:\n            raise ValueError("FRED_API_KEY is not set in the environment variables.")\n            \n    def download_macro_data(self, series_id: str, start_date: str) -> pd.DataFrame:\n        """\n        Downloads macroeconomic data for a given FRED series ID.\n        \n        Args:\n            series_id (str): The FRED series ID (e.g., 'FEDFUNDS', 'CPIAUCSL').\n            start_date (str): The start date for the data (YYYY-MM-DD).\n            \n        Returns:\n            pd.DataFrame: DataFrame containing the macroeconomic data.\n        """\n        print(f"Downloading FRED data for series {series_id} starting from {start_date}...")\n        \n        save_dir = Path("data/external")\n        save_dir.mkdir(parents=True, exist_ok=True)\n        file_path = save_dir / f"{series_id}.csv"\n        \n        # Return empty DataFrame as placeholder\n        return pd.DataFrame()\n''',

    "src/data/data_merger.py": '''"""\nModule for merging market and macroeconomic data.\n"""\n\nimport pandas as pd\n\ndef merge_market_and_macro(df_prices: pd.DataFrame, df_macro: pd.DataFrame) -> pd.DataFrame:\n    """\n    Merges intraday price data with daily macroeconomic data using forward fill.\n    \n    Args:\n        df_prices (pd.DataFrame): DataFrame with intraday price data.\n        df_macro (pd.DataFrame): DataFrame with daily macroeconomic data.\n        \n    Returns:\n        pd.DataFrame: The merged DataFrame.\n    """\n    print("Merging intraday prices with macroeconomic data using forward fill...")\n    \n    # Placeholder for merging logic\n    return pd.DataFrame()\n''',

    "src/features/technical.py": '''"""\nModule for calculating technical indicators.\n"""\n\nimport pandas as pd\nimport numpy as np\n\ndef calculate_rsi(df: pd.DataFrame, period: int = 14, price_col: str = 'close') -> pd.Series:\n    """\n    Calculates the Relative Strength Index (RSI).\n    \n    Args:\n        df (pd.DataFrame): Input dataframe containing price data.\n        period (int): Lookback period for RSI calculation.\n        price_col (str): The column to use for price.\n        \n    Returns:\n        pd.Series: A series containing the RSI values.\n    """\n    pass\n\ndef calculate_atr(df: pd.DataFrame, period: int = 14, high_col: str = 'high', low_col: str = 'low', close_col: str = 'close') -> pd.Series:\n    """\n    Calculates the Average True Range (ATR).\n    \n    Args:\n        df (pd.DataFrame): Input dataframe.\n        period (int): Lookback period for ATR.\n        high_col (str): Column name for high prices.\n        low_col (str): Column name for low prices.\n        close_col (str): Column name for close prices.\n        \n    Returns:\n        pd.Series: A series containing the ATR values.\n    """\n    pass\n\ndef calculate_sma(df: pd.DataFrame, period: int, price_col: str = 'close') -> pd.Series:\n    """\n    Calculates the Simple Moving Average (SMA) for a specific timeframe (e.g., 1H, 4H).\n    \n    Args:\n        df (pd.DataFrame): Input dataframe.\n        period (int): Lookback period for SMA.\n        price_col (str): Column name for price.\n        \n    Returns:\n        pd.Series: A series containing the SMA values.\n    """\n    pass\n''',

    "src/features/patterns.py": '''"""\nModule for detecting chart patterns.\n"""\n\nimport pandas as pd\n\ndef detect_bill_williams_fractals(df: pd.DataFrame, high_col: str = 'high', low_col: str = 'low') -> pd.DataFrame:\n    """\n    Detects Bill Williams Fractals (Up and Down) in the price series.\n    \n    Args:\n        df (pd.DataFrame): Input dataframe containing high and low prices.\n        high_col (str): Column name for high prices.\n        low_col (str): Column name for low prices.\n        \n    Returns:\n        pd.DataFrame: DataFrame with boolean columns indicating Up and Down fractals.\n    """\n    pass\n\ndef detect_wick_reclaims(df: pd.DataFrame, open_col: str = 'open', high_col: str = 'high', low_col: str = 'low', close_col: str = 'close') -> pd.Series:\n    """\n    Detects wick reclaims/rejections.\n    \n    Args:\n        df (pd.DataFrame): Input dataframe containing OHLC data.\n        open_col, high_col, low_col, close_col (str): Names of OHLC columns.\n        \n    Returns:\n        pd.Series: A series indicating occurrences of wick reclaims.\n    """\n    pass\n''',

    "src/models/xgboost_filter.py": '''"""\nModule for the XGBoost asset selection filter.\n"""\n\nimport pandas as pd\nimport numpy as np\nimport xgboost as xgb\n\nclass TradeSelectorXGB:\n    """\n    Class implementing an XGBoost model to filter and select viable trades.\n    """\n    \n    def __init__(self, model_params: dict = None):\n        """\n        Initializes the XGBoost model with given parameters.\n        \n        Args:\n            model_params (dict): Hyperparameters for the XGBoost classifier/regressor.\n        """\n        self.params = model_params if model_params else {}\n        self.model = None # xgb.XGBClassifier(**self.params) or XGBRegressor\n\n    def train_model(self, X_train: pd.DataFrame, y_train: pd.Series):\n        """\n        Trains the XGBoost model.\n        \n        Args:\n            X_train (pd.DataFrame): Features for training.\n            y_train (pd.Series): Target variable for training.\n        """\n        pass\n\n    def predict_prob(self, X_test: pd.DataFrame) -> np.ndarray:\n        """\n        Predicts probabilities or scores for new data.\n        \n        Args:\n            X_test (pd.DataFrame): Features for prediction.\n            \n        Returns:\n            np.ndarray: Predicted probabilities.\n        """\n        pass\n\n    def get_feature_importance(self) -> pd.DataFrame:\n        """\n        Evaluates and returns the importance of variables used in the model.\n        \n        Returns:\n            pd.DataFrame: DataFrame containing feature names and their importance scores.\n        """\n        pass\n''',

    "src/models/agent_logic.py": '''"""\nModule for the Autonomous Agent logic deciding portfolio allocations.\n"""\n\nimport pandas as pd\n\nclass PortfolioAgent:\n    """\n    Autonomous Agent that decides portfolio weights, rebalancing, and risk control.\n    """\n    \n    def __init__(self):\n        """\n        Initializes the Portfolio Agent.\n        """\n        pass\n\n    def calculate_weights(self, predictions: dict, current_portfolio: dict, risk_metrics: dict) -> dict:\n        """\n        Decides capital allocation for each asset based on model predictions and risk metrics.\n        \n        Args:\n            predictions (dict): Model outputs/scores for available assets.\n            current_portfolio (dict): Current holdings and cash state.\n            risk_metrics (dict): Current risk context (ATR, Volatility).\n            \n        Returns:\n            dict: Target weights or allocations for the assets.\n        """\n        pass\n''',

    "src/environment/portfolio.py": '''"""\nModule for tracking portfolio state.\n"""\n\nclass Portfolio:\n    """\n    Maintains the state of capital, available cash, open positions, and applies trading commissions.\n    """\n    \n    def __init__(self, initial_capital: float = 100000.0, commission_rate: float = 0.001):\n        """\n        Initializes the portfolio.\n        \n        Args:\n            initial_capital (float): Starting capital for the simulation.\n            commission_rate (float): Commission rate applied per trade (e.g., 0.1%).\n        """\n        self.initial_capital = initial_capital\n        self.current_capital = initial_capital\n        self.cash = initial_capital\n        self.positions = {}\n        self.commission_rate = commission_rate\n\n    def execute_trade(self, ticker: str, quantity: float, price: float, side: str):\n        """\n        Executes a trade and updates cash, positions, and accounts for commissions.\n        \n        Args:\n            ticker (str): The asset ticker.\n            quantity (float): Number of shares/units.\n            price (float): Execution price.\n            side (str): 'BUY' or 'SELL'.\n        """\n        pass\n        \n    def get_portfolio_value(self, current_prices: dict) -> float:\n        """\n        Calculates the total value of the portfolio (cash + positions value).\n        \n        Args:\n            current_prices (dict): Latest prices for the held assets.\n            \n        Returns:\n            float: Total portfolio value.\n        """\n        return self.cash\n''',

    "src/environment/risk_manager.py": '''"""\nModule for risk management calculations.\n"""\n\nclass RiskManager:\n    """\n    Calculates position sizes based on ATR and controls maximum drawdown per trade.\n    """\n    \n    def __init__(self, max_drawdown_per_trade: float = 0.02, atr_multiplier: float = 2.0):\n        """\n        Initializes the RiskManager.\n        \n        Args:\n            max_drawdown_per_trade (float): Max percentage risk allowed per trade.\n            atr_multiplier (float): Multiplier for ATR to set stop loss.\n        """\n        self.max_risk_pct = max_drawdown_per_trade\n        self.atr_multiplier = atr_multiplier\n\n    def calculate_position_size(self, capital: float, current_price: float, atr_value: float) -> float:\n        """\n        Determines the appropriate position size for a trade based on account capital and ATR.\n        \n        Args:\n            capital (float): Total portfolio capital.\n            current_price (float): Current asset price.\n            atr_value (float): Current ATR value for the asset.\n            \n        Returns:\n            float: The recommended position size (quantity).\n        """\n        pass\n''',

    "src/environment/backtester.py": '''"""\nModule for backtesting simulation.\n"""\n\nimport pandas as pd\nfrom src.environment.portfolio import Portfolio\nfrom src.environment.risk_manager import RiskManager\nfrom src.models.agent_logic import PortfolioAgent\n\nclass Backtester:\n    """\n    Iterates through historical data row by row, simulating an event-driven backtest.\n    """\n    \n    def __init__(self, portfolio: Portfolio, risk_manager: RiskManager, agent: PortfolioAgent):\n        """\n        Initializes the Backtester.\n        \n        Args:\n            portfolio (Portfolio): Instance of the portfolio.\n            risk_manager (RiskManager): Instance of the risk manager.\n            agent (PortfolioAgent): Instance of the trading agent.\n        """\n        self.portfolio = portfolio\n        self.risk_manager = risk_manager\n        self.agent = agent\n        self.equity_curve = []\n\n    def run(self, df_data: pd.DataFrame, model):\n        """\n        Runs the backtest simulation over the provided data dataframe.\n        \n        Args:\n            df_data (pd.DataFrame): The merged dataframe of historical market and macro data.\n            model: The trained predictive model (e.g., TradeSelectorXGB).\n        """\n        print("Starting backtest iteration...")\n        pass\n        \n    def get_equity_curve(self) -> pd.Series:\n        """\n        Returns the recorded equity curve.\n        """\n        return pd.Series(self.equity_curve)\n''',

    "src/evaluation/metrics.py": '''"""\nModule for calculating financial performance metrics.\n"""\n\nimport pandas as pd\nimport numpy as np\n\ndef calculate_sharpe_ratio(returns: pd.Series, risk_free_rate: float = 0.0) -> float:\n    """\n    Calculates the Sharpe Ratio of the strategy returns.\n    \n    Args:\n        returns (pd.Series): Series of periodic returns.\n        risk_free_rate (float): The baseline risk-free rate.\n        \n    Returns:\n        float: The Sharpe Ratio.\n    """\n    pass\n\ndef calculate_max_drawdown(equity_curve: pd.Series) -> float:\n    """\n    Calculates the Maximum Drawdown from the equity curve.\n    \n    Args:\n        equity_curve (pd.Series): Series representing portfolio value over time.\n        \n    Returns:\n        float: The Maximum Drawdown as a percentage.\n    """\n    pass\n\ndef calculate_sortino_ratio(returns: pd.Series, risk_free_rate: float = 0.0, target_return: float = 0.0) -> float:\n    """\n    Calculates the Sortino Ratio focusing on downside deviation.\n    \n    Args:\n        returns (pd.Series): Series of periodic returns.\n        risk_free_rate (float): The baseline risk-free rate.\n        target_return (float): The minimum acceptable return.\n        \n    Returns:\n        float: The Sortino Ratio.\n    """\n    pass\n''',

    "src/evaluation/plotting.py": '''"""\nModule for generating performance plots.\n"""\n\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom pathlib import Path\n\ndef plot_equity_curve(strategy_equity: pd.Series, benchmark_equity: pd.Series, save_name: str = "equity_curve.png"):\n    """\n    Generates a plot comparing the strategy's equity curve against a benchmark (e.g., SPY)\n    and saves it to the results/figures/ folder.\n    \n    Args:\n        strategy_equity (pd.Series): Equity curve of the portfolio.\n        benchmark_equity (pd.Series): Equity curve of the benchmark.\n        save_name (str): The filename for the saved plot.\n    """\n    save_dir = Path("results/figures")\n    save_dir.mkdir(parents=True, exist_ok=True)\n    file_path = save_dir / save_name\n    \n    plt.figure(figsize=(10, 6))\n    # plt.plot(strategy_equity, label='Strategy')\n    # plt.plot(benchmark_equity, label='Benchmark')\n    plt.title("Strategy vs Benchmark Equity Curve")\n    plt.xlabel("Date")\n    plt.ylabel("Portfolio Value")\n    plt.legend()\n    plt.grid(True)\n    \n    plt.savefig(file_path)\n    plt.close()\n'''
}

files.update(file_contents)

for file_path, content in files.items():
    full_path = base_path / file_path
    full_path.parent.mkdir(parents=True, exist_ok=True)
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(content)

print("Project structure created successfully.")
